"""生成新的 Alembic 迁移脚本

Revision ID: 881e1d5ed06d
Revises: 627df3b369d6
Create Date: 2025-03-15 21:42:25.207417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '881e1d5ed06d'
down_revision: Union[str, None] = '627df3b369d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
